# E-Commerce Sales Analysis using Pandas

This project explores an e-commerce dataset using Python and Pandas to answer business questions and practice data analysis skills.

In [1]:
import pandas as pd
import numpy as np
pd.set_option('Display.max_columns',None)

In [ ]:
df = pd.read_csv('E-Commerce Sales.csv')
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

## Display first 10 Rows of the dataset

In [3]:
# Task 1: Display first 10 Rows of the dataset
# To access the top 10 rows we use head() function
df.head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63

## Display last 10 Rows of the dataset

In [ ]:
# Task 2: Display last 10 Rows of the dataset
# To access the last 10 rows we use tail() function
df.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

## Check data type of each column

In [ ]:
# Task 3: Check the type of columns
# To check the datatype of each column we use dtypes attribute
print('Datatype of each column in the dataset')
print('------------------------------------------')
print(df.dtypes)

Datatype of each column in the dataset
------------------------------------------
Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

## Check number of null values in each column

In [6]:
# Task 4: Check number of null values in each column
# To check the number of null values in each column we use isna() and sum() functions
print('Null values in each column')
print('------------------------------------------------')
df.isna().sum()

Null values in each column
------------------------------------------------

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

## Find total number of rows and  columns in the Dataset

In [7]:
# Task 5: Find total number of rows and  columns in the Dataset
# To find total number of rows and columns in the dataset we use shape attribute
print('Total number of Rows and columns in the Dataset')
print('-----------------------------------------------')
for rows,columns in [df.shape]:
    print('Number of rows =',rows)
    print('Number of columns =',columns)

Total number of Rows and columns in the Dataset
-----------------------------------------------
Number of rows = 10000
Number of columns = 14

## Find the highest and lowest PurchasePrices

In [8]:
# Task 6: Find the highest and lowest PurchasePrices
# To find maximum and minimum purchase prices we use min() and max() functions
print('-----------------------------------------------------------------------')
print('Lowest Purchase Price')
print('-----------------------------------------------------------------------')
print(df[df['Purchase Price']==df['Purchase Price'].min()]['Purchase Price'])
print('-----------------------------------------------------------------------')
print('Highest Purchase Prices')
print('-----------------------------------------------------------------------')
print(df[df['Purchase Price']==df['Purchase Price'].max()]['Purchase Price'])

-----------------------------------------------------------------------
Lowest Purchase Price
-----------------------------------------------------------------------
2876    0.0
5487    0.0
Name: Purchase Price, dtype: float64
-----------------------------------------------------------------------
Highest Purchase Prices
-----------------------------------------------------------------------
2092    99.99
7807    99.99
Name: Purchase Price, dtype: float64

## Find the average purchase price

In [9]:
# Task 7: Find the average purchase price
# To find the average we use mean() function
print('Average Purchase price =',df['Purchase Price'].mean())

Average Purchase price = 50.347302

## How many people using French 'fr' language

In [10]:
# Task 8: How many people using French 'fr' language
# To find how many people using french language we access the data of language using French
# Then we find the length of the data 
print('Number of people using french as their language',len(df[df['Language']=='fr']))

Number of people using french as their language 1097

## Find the JobTitle contains engineer

In [ ]:
# Task 9: Find the JobTitle contains engineer
# To find the jobtitle containing engineer we access the Job column then obtain the job titles with engineer
print('Job Titles containing engineer')
print('------------------------------------------')
print(df[df['Job'].str.contains('engineer')]['Job'])

Job Titles containing engineer
------------------------------------------
1               Drilling engineer
3               Drilling engineer
50            Mechanical engineer
103      Technical sales engineer
193               Energy engineer
                  ...
9934    Consulting civil engineer
9948          Structural engineer
9970          Electrical engineer
9977          Biomedical engineer
9996              Energy engineer
Name: Job, Length: 531, dtype: object

## Find the email of the person with the IP Address: 132.207.160.22F

In [ ]:
# Task 10: Find the email of the person with the IP Address: 132.207.160.22F
# To obtain the email of the IP address given we access the data of the IP Address then access the email column
print('Email of the IP Address:132.207.160.22')
print('-------------------------------------------------')
print(df[df['IP Address']=='132.207.160.22']['Email'])

Email of the IP Address:132.207.160.22
-------------------------------------------------
2    amymiller@morales-harrison.com
Name: Email, dtype: object

## How many people has master card as their credit card provider and made a purchase above 50

In [ ]:
# Task 11: How many people has master card as their credit card provider and made a purchase above 50
# To find number of people using Master card and purchase prices above 50
# Convert the Purchase Price column to float  and then we use conditional statements to obtain number of people
print('Number of people using Mastercard and PurchasePrice is above 50 =',df[(df['CC Provider']=='Mastercard')&(df['Purchase Price'] > 50)].shape[0])

Number of people using Mastercard and PurchasePrice is above 50 = 405

## Find the email of the person with the following Credit Card Number: 4664825258997302

In [14]:
# Task 12: Find the email of the credit card number:4664825258997302
# To find the email of the credit card user we directly access the card user then obtain email column
print('Email of the credit card number:4664825258997302')
print('---------------------------------------------------')
print(df[df['Credit Card']==4664825258997302]['Email'])

Email of the credit card number:4664825258997302
---------------------------------------------------
9992    bberry@wright.net
Name: Email, dtype: object

##  How many people purchase during the AM and how many people purchase during PM

In [15]:
# Task 13: How many people purchase during the AM and how many people purchase during PM
# To find number purchases at AM and PM we use value_counts() function
print('Number of people purchasing during AM and PM')
print('-----------------------------------------------------')
df['AM or PM'].value_counts()

Number of people purchasing during AM and PM
-----------------------------------------------------

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

## How many people have a credit card that expires in 2020

In [16]:
# Task 14: How many people have a credit card that expires in 2020
# To find number of people have a credit card that expires in 2020 should access the data of exp date column ending with 2020
# Then using shape attribute we can obtain count of people
print('Number of people credit card expires in 2020 =',df[df['CC Exp Date'].str.endswith('20')].shape[0])

Number of people credit card expires in 2020 = 988

## Find the Address of top 5 highest purchase prices

In [17]:
# Task 15: Find the Address of top 5 highest purchase prices
# To find the address of top 5 highest purchase prices use nlargest() function and access the Address
df.nlargest(5,'Purchase Price')['Address']

2092            63773 Shelton Greens\nAshleyton, MA 00493
7807                PSC 6177, Box 1004\nAPO AA 57143-1269
9856    058 Miranda Locks Suite 792\nPort Davidstad, P...
7604              672 James Oval\nNew Davidview, KS 91202
3844    27148 Kathy Cliff Apt. 400\nEast Jillton, TX 5...
Name: Address, dtype: object

## What are the top 5 most popular email providers (e.g. gmail.com, yahoo.com, etc...)

In [ ]:
# Task 16: What are the top 5 most popular email providers
# To find the top 5 most popular email providers --> first access the Email column
# Use split() to separate the email provider name then access the number of unique values using value_counts()
# Use head() to access top 5
df['Email'].str.split('@').str[1].value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

## Conclusion

In this project, I used Pandas to perform exploratory data analysis on an e-commerce dataset. I practiced filtering, aggregation, string operations, sorting, and extracting business insights from data.